apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qco2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qco2
    app.kubernetes.io/part-of: ci10t-777-0061-app
  name: devfile-sample-qco2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qco2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qco2
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0061-tenant/ci10t-777-0061-app/devfile-sample-qco2@sha256:3d330e3d013a09c2ac8fd3cdc1003bf6e955a5f385b82143615e998b31b720de
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
